### ISSUE TITLE
Bump test coverage to 100%

### ISSUE THREAD

**Issue by mourner** [mafintosh/length-prefixed-stream#1]
Running istanbul coverage, it reports 87.5% for code branches, which is great but with just a few things missing:
- decoding longer varints (all tests have 1-byte lengths)
- decoding varints split across chunks
- encoding enough messages to overflow the buffer pool

Covering these cases will bump it to 100%.

**Comment by mafintosh** [comment]
added tests for all those things :)

**Comment by mourner** [comment]
Beautiful, thank you!

**Comment by mourner** [comment]
@mafintosh note that the build is failing after recent commits. https://travis-ci.org/mafintosh/length-prefixed-stream/builds
BTW you should also add `sudo: false` to Travis config to switch it to the new infrastructure.

**Comment by mafintosh** [comment]
fixed!
