### ISSUE TITLE
Problem with crypto

### ISSUE THREAD

**Issue by JacopoDaeli** [mafintosh/length-prefixed-stream#3]
Hey @mafintosh,

I am having a trouble using this module with crypto cipher/decipher.

Basically,

```
const crypto = require('crypto')
const lpstream = require('length-prefixed-stream')

const cipher = crypto.createCipher('aes192', 'a password')
const decipher = crypto.createDecipher('aes192', 'a password')

const encode = lpstream.encode() // create an encode stream to send data
const decode = lpstream.decode() // create an decode stream to receive data

encode.write('hello world')
encode.write('hello world_2')
encode.write('END_OF_STREAM')

decode.on('data', function(data) {
  console.log(data.toString())
})

encode.pipe(cipher).pipe(decipher).pipe(decode)
```

it only prints `hello world`. `decode` seems  not receiving the last two `encode.write()` operations.

Any idea?

**Comment by mafintosh** [comment]
is aes interactive? otherwise you might have to call encode.end() for it to flush

**Comment by JacopoDaeli** [comment]
What `aes interactive` means? Anyway, if I call `encode.end()` works.

**Comment by JacopoDaeli** [comment]
Update my comment above. My bad. All good with it.

**Comment by mafintosh** [comment]
did you get it to work?

**Comment by JacopoDaeli** [comment]
Calling `encode.end()` in my example definitely makes the job. But when I get in my real case, sometime works and sometimes it doesn't. I send you more details tomorrow, and let's see if you can help me out :-) Time to go to sleep for me. 2.15 am here in London.

**Comment by JacopoDaeli** [comment]
@mafintosh if I flush the stream, yes it works. To flus by the way I have to call `.end()` method as you said. The problem, which I am not sure if it's a real problem, it's a problem for me because of [Error: UTP_ECONNRESET](https://github.com/mafintosh/utp-native/issues/5) (Remember?).

In my real word I have in fact something like that:

```
encode.pipe(cipher).pipe(utpSocket).pipe(decipher).pipe(decode)
```

To be more precise, I need to take [this example](https://github.com/JacopoDaeli/udtp/blob/master/example.js) I wrote with `utp-native` and cypher  the stream before sending it over the net.

**Comment by JacopoDaeli** [comment]
@mafintosh just found a workaround which seems a very clean solution btw.

```
    readableStream.on('data', chunk => {
      encoder.write(chunk)
    })

    readableStream.on('end', () => {
      encoder.write('END_OF_FILE')
      encoder.end()
    })

    encoder.on('data', chunk => {
      cipher.write(chunk)
    })

    encoder.on('end', () => {
      cipher.end()
    })

    cipher.on('readable', () => {
      const chunk = cipher.read()
      if (chunk) utpSocket.write(chunk)
    })
```

This works, and the uptSocket is closed server side once the server receive the `END_OF_FILE`. Does make sense to you?
