### ISSUE TITLE
document encoding format

### ISSUE THREAD

**Issue by derhuerst** [mafintosh/length-prefixed-stream#8]
I want to use this lib to stream [GTFS-RT](https://developers.google.com/transit/gtfs-realtime/reference/) `FeedMessage` protocol buffers.

In order to make the stream accessible for people outside the JavaScript ecosystem, I'd like to document the `length-prefixed-stream` "wire format" by just linking to `varint` and giving an example. What do you think?

**Comment by mafintosh** [comment]
Great idea! PR if you are up for it
